new_cv_model <- function(predictors,
                         outcome,
                         model_func,
                         predict_func,
                         perf_func,
                         SESOI_lower,
                         SESOI_upper,
                         model,
                         predicted,
                         residual,
                         residual_magnitude,
                         performance,
                         cross_validation,
                         extra = NULL,
                         control,
                         na.rm,
                         blueprint) {
  hardhat::new_model(
    predictors = predictors,
    outcome = outcome,
    model_func = model_func,
    predict_func = predict_func,
    perf_func = perf_func,
    SESOI_lower = SESOI_lower,
    SESOI_upper = SESOI_upper,
    model = model,
    predicted = predicted,
    residual = residual,
    residual_magnitude = residual_magnitude,
    performance = performance,
    cross_validation = cross_validation,
    extra = extra,
    control = control,
    na.rm = na.rm,
    blueprint = blueprint,
    class = "bmbstats_cv_model"
  )
}
